version: "3"

services:
  authentication-service:
    build:
      context: ./authentication-service
    command: sh ./docker-entrypoint.sh
    restart: always
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_HOST: postgres
      POSTGRES_DATABASE: $AUTH_DB
    depends_on:
      - postgres
    ports:
      - 3000:3000
    volumes:
      - ./authentication-service/:/usr/app/
      - /usr/app/node_modules

  postgres:
    build: ./postgres-config
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USERNAME
      POSTGRES_DB_LIST: $POSTGRES_DB_LIST
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres